import { test, expect } from '@playwright/test';
import { finishOnboarding } from './helpers.js';

test('desktop and mobile scenes render their actual models', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('.world-loading')).toHaveCount(0);
  await finishOnboarding(page);
  await page.getByRole('button', { name: '建造', exact: true }).click();
  await expect(page.locator('.catalog-item img').first()).toBeVisible();
  await page.waitForTimeout(1400);
  const desktop = await page.evaluate(() => window.__sunny.diagnostics());
  console.log('DESKTOP', desktop);
  expect(new Set(desktop.samples.map(p => p.join(','))).size).toBeGreaterThan(3);
  expect(desktop.triangles).toBeGreaterThan(10000);
  expect(desktop.calls).toBeLessThan(1000);
  await page.screenshot({ path: 'test-results/desktop-build.png' });
  const beforeCamera = await page.evaluate(() => window.__sunny.project(0, 0.25, 0));
  await page.getByRole('button', { name: '旋转视角', exact: true }).click();
  await page.waitForTimeout(850);
  const afterCamera = await page.evaluate(() => window.__sunny.project(0, 0.25, 0));
  expect(Math.hypot(afterCamera.x - beforeCamera.x, afterCamera.y - beforeCamera.y)).toBeGreaterThan(3);
  await page.getByRole('button', { name: '回到家园视角', exact: true }).click();
  await page.getByRole('button', { name: '角色', exact: true }).click();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/desktop-avatar.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/mobile-avatar.png' });
  await page.getByRole('button', { name: '建造', exact: true }).click();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/mobile-build.png' });
  console.log('MOBILE', await page.evaluate(() => ({ diagnostics: window.__sunny.diagnostics(), scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth })));
  await page.setViewportSize({ width: 360, height: 740 });
  await page.waitForTimeout(750);
  await page.screenshot({ path: 'test-results/small-mobile-build.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(360);
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.waitForTimeout(750);
  await page.screenshot({ path: 'test-results/wide-build.png' });
  expect(await page.locator('img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  expect(errors).toEqual([]);
});
